# Generated by Django 2.2.12 on 2021-07-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokeFileDownLoadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
