# Generated by Django 2.2.12 on 2021-08-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokeFileDownLoadModel',
            new_name='PokeFilesModel',
        ),
    ]
